# TODO this is tied to the cloud provider
provider: ${dns_provider}

env:
%{ for key in keys(keys) ~}
  - name: ${key}
    valueFrom:
      secretKeyRef:
        name: external-dns-${dns_provider}
        key: ${key}
%{ endfor ~}

sources:
  - service
  - ingress

domainFilters:
  - ${cluster_domain}

policy: sync

registry: txt
txtOwnerId: external-dns
txtPrefix: external-dns-

logLevel: info
logFormat: json

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
