apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ${name}
spec:
  acme:
    server: ${server}
    email: ${email}
    privateKeySecretRef:
      name: ${name}
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: ${secret_name}
            key: api-token
