apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ${name}
spec:
  acme:
    server: ${server}
    email: ${email}
    privateKeySecretRef:
      name: ${name}
    solvers:
    - dns01:
        webhook:
          groupName: acme.scaleway.com
          solverName: scaleway
          config:
            accessKeySecretRef:
              name: ${secret_name}
              key: SCW_ACCESS_KEY
            secretKeySecretRef:
              name: ${secret_name}
              key: SCW_SECRET_KEY
