apiVersion: v1
kind: Secret
metadata:
  name: ozone-secrets
  namespace: ${namespace}
type: Opaque
stringData:
  OZONE_DB_POSTGRES_URL: "postgresql://ozone_user:${db_password_urlencoded}@${postgres_cluster_name}-rw.${postgres_namespace}.svc.cluster.local:5432/ozone?sslmode=require"
  OZONE_ADMIN_PASSWORD: "${ozone_admin_password}"
  OZONE_SIGNING_KEY_HEX: "${ozone_signing_key_hex}"
