apiVersion: v1
kind: Secret
metadata:
  name: litestream-credentials
  namespace: ${namespace}
  labels:
    app: pds
    app.kubernetes.io/name: pds
    app.kubernetes.io/component: backup
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "${backup_access_key_id}"
  AWS_SECRET_ACCESS_KEY: "${backup_secret_access_key}"

# TODO: Add app.kubernetes.io/version label for tracking deployments
# TODO: Add app.kubernetes.io/managed-by: "terraform" label for ownership tracking
# TODO: Consider adding AWS_SESSION_TOKEN if using temporary credentials (STS/IAM roles)
