apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-backup-secret-reader
  namespace: ${namespace}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames:
      - ${secret_name}
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-backup-secret-reader
  namespace: ${namespace}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: postgres-backup-secret-reader
subjects:
  - kind: ServiceAccount
    name: postgres-cluster
    namespace: ${namespace}
