{
 "title": "Ingress-NGINX Analytics (GeoIP)",
 "description": "Loki showcase using JSON ingress-nginx access logs with GeoIP2 data",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "KPI's", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Unique user visits ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by (remote_addr) (count_over_time({namespace=\"ingress-nginx\"} != \"Hyperping\" | json |  __error__=\"\" [1h])))"
    }
   ]
  },
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 12, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({namespace=\"ingress-nginx\"} != \"Hyperping\" | json |  __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status: {{status}}"
    }
   ]
  },
  {
   "title": "Total requests  ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({namespace=\"ingress-nginx\"}[$__interval]))  "
    }
   ]
  },
  {
   "title": "Unique user visits ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by (remote_addr) (count_over_time({namespace=\"ingress-nginx\"} != \"Hyperping\" | json |  __error__=\"\" [24h])))"
    }
   ]
  },
  {
   "title": "% of 5xx requests ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " sum(rate({namespace=\"ingress-nginx\"} != \"Hyperping\" | json | status >= 500 |__error__=\"\"[$__interval])) / (sum(rate({namespace=\"ingress-nginx\"} != \"Hyperping\" | json | __error__=\"\"[$__interval])) / 100)"
    }
   ]
  },
  {
   "title": "% of requests by Googlebot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": " sum(rate(({namespace=\"ingress-nginx\"} |= \"Googlebot\")[$__interval])) / (sum(rate(({namespace=\"ingress-nginx\"} != \"Googlebot\")[$__interval])) / 100)"
    }
   ]
  },
  {
   "title": "Unique user visits ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by (remote_addr) (count_over_time({namespace=\"ingress-nginx\"} != \"Hyperping\" | json |  __error__=\"\" [48h])))"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (host) (sum_over_time({namespace=\"ingress-nginx\"} != \"Hyperping\" | json | status=200 | unwrap body_bytes_sent |  __error__=\"\" [$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "Visitor Heat Map (Lat/Long)",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 11, "x": 0, "y": 13 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"ingress-nginx\"} != \"Hyperping\" | json"
    }
   ]
  },
  {
   "title": "Recent requests",
   "type": "logs",
   "gridPos": { "h": 16, "w": 13, "x": 11, "y": 13 },
   "targets": [
    {
     "expr": "{namespace=\"ingress-nginx\"} != \"Hyperping\" | json | line_format \"request for {{.request_uri}} with HTTP status: {{.status}} from {{.remote_addr}} located {{.geoip_country_code}} \""
    }
   ]
  },
  { "title": "Request statistics over time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "95th percentile of Request Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.95,{namespace=\"ingress-nginx\"} != \"Hyperping\" | json | unwrap request_time |  __error__=\"\"  [$__interval]) by (host)",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "max by (host) (max_over_time({namespace=\"ingress-nginx\"} != \"Hyperping\" | json | unwrap request_time |  __error__=\"\"  [$__interval]))",
     "legendFormat": "max latency"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 30 },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({namespace=\"ingress-nginx\"} != \"Hyperping\" | json |  __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status {{status}}"
    }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 30 },
   "targets": [
    {
     "expr": "sum by (host) (sum_over_time({namespace=\"ingress-nginx\"} != \"Hyperping\" | json | status=200 | unwrap body_bytes_sent |  __error__=\"\" [$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  { "title": "Acquisition and Behaviour", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Top User Agents",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "topk(10, sum by (http_user_agent) (count_over_time({namespace=\"ingress-nginx\"} != \"Hyperping\" | json |  __error__=\"\" [$__interval])))",
     "legendFormat": "{{http_user_agent}}"
    }
   ]
  },
  {
   "title": "Top HTTP Referers",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 40 },
   "targets": [
    {
     "expr": "topk(20, sum by (http_referer) (count_over_time({namespace=\"ingress-nginx\"} != \"Hyperping\" | json |  http_referer != \"\" and http_referer !~ \".*?$host.*?\" | __error__=\"\" [$__interval])))",
     "legendFormat": "{{http_referer}}"
    }
   ]
  },
  {
   "title": "Top IPs",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "topk(10, sum by (remote_addr) (count_over_time({namespace=\"ingress-nginx\"} != \"Hyperping\" | json |  __error__=\"\" [$__interval])))",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  },
  {
   "title": "Top Requested Pages",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 46 },
   "targets": [
    {
     "expr": "topk(5,sum by (request_uri) (count_over_time({namespace=\"ingress-nginx\"} != \"Hyperping\" | json | request_uri != \"/\" | __error__=\"\" [$__interval])))",
     "legendFormat": "{{request_uri}}"
    }
   ]
  }
 ]
}